
import {
    BadgePercentIcon,
    BarChart2Icon,
    BellIcon,
    ChevronDown,
    ChevronLeft,
    ChevronRightIcon,
    ChevronsLeftIcon,
    ChevronsRightIcon,
    ClipboardListIcon,
    CreditCardIcon,
    HelpCircleIcon,
    HomeIcon,
    LayoutGridIcon,
    MousePointer2Icon,
    PackageCheckIcon,
    PaletteIcon,
    SearchIcon,
    TruckIcon,
    Users,
    Wallet,
    ZapIcon,
    X,
    DownloadIcon,
    ArrowDownUpIcon,
    AlertCircleIcon,
    type LucideIcon
} from 'lucide-react';

export type Icon = LucideIcon;

export const Icons = {
    Home: HomeIcon,
    ChevronLeft: ChevronLeft,
    ChevronDown: ChevronDown,
    ChevronRight: ChevronRightIcon,
    ChevronsLeft: ChevronsLeftIcon,
    ChevronsRight: ChevronsRightIcon,
    ClipboardList: ClipboardListIcon,
    LayoutGrid: LayoutGridIcon,
    Truck: TruckIcon,
    BarChart2: BarChart2Icon,
    CreditCard: CreditCardIcon,
    MousePointer2: MousePointer2Icon,
    BadgePercent: BadgePercentIcon,
    Users: Users,
    Palette: PaletteIcon,
    Zap: ZapIcon,
    PackageCheck: PackageCheckIcon,
    Wallet: Wallet,
    HelpCircle: HelpCircleIcon,
    Search: SearchIcon,
    Bell: BellIcon,
    Close: X,
    Download: DownloadIcon,
    Sort: ArrowDownUpIcon,
    AlertCircle: AlertCircleIcon
}